project:
  type: website
  output-dir: docs

website:
  title: "Lily Bentley"
  description: "Movement ecologist, R enthusiast, postdoctoral research fellow"
  site-url: https://lilybentley.github.io   # change to your GitHub username
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: https://scholar.google.com/citations?user=ZLBy3hIAAAAJ&hl=en
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: outreach.qmd
        text: Outreach
    right:
      - icon: linkedin
        href: https://au.linkedin.com/in/lily-bentley-45000776
        aria-label: LinkedIn
      - icon: twitter-x
        href: http://www.twitter.com/lilybentley
        aria-label: X / Twitter
  page-footer:
    left: "© 2026 Lily Bentley"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    link-external-newwindow: true
