---
title: "Research"
---

## Current work

Quantifying global migratory connectivity of marine megafauna, and establishing methods to build migratory network models by integrating multiple data collection methods.

I work on [Blue Corridors for Turtles](https://www.argos-system.org/new-global-initiative-map-blue-corridors-for-turtles/) with WWF and partners, combining satellite tracking and genetic data to map the movements of all seven sea turtle species and identify Important Marine Turtle Areas. Read the [June 2025 report](https://wwfafrica.awsassets.panda.org/downloads/blue-corridors-for-turtles_report.pdf).

I'm also tracking seabirds in the Great Barrier Reef with BirdLife Australia and Queensland Parks and Wildlife Service.

I have been invited to review for journals including *Animal Behaviour*, *Conservation Biology* and *MEPS*.

## PhD

My PhD (completed 2022) used a substantial body of existing [seabird tracking data](https://www.seabirdtracking.org) to determine the role of habitat accessibility and preference in explaining variation in distribution patterns, both within and between seabird species.

## Research assistant

I conducted quality assurance and control on several seabird population distribution databases (spanning 500 individual populations and 60 years) in preparation for further analysis.

## Honours

I investigated the physiological and environmental factors influencing the field body temperature and movement patterns of estuarine crocodiles in the Wenlock River system, Northern Queensland. This project involved refining and analysing over 9 million raw data points in R (including GAM, GLMM, and FFT analyses, and data visualisation using ggplot2).

## Undergraduate project

I studied the frequency of [skin sloughing](https://www.youtube.com/watch?v=sfGbbovgsdQ) in two native Australian amphibians, and its relationship with body size.

## Volunteering

I've also assisted with data collection for projects on kangaroo social behaviour and endocrinology, as well as native fish passage through culverts.

For publications, see my [Google Scholar profile](https://scholar.google.com/citations?user=ZLBy3hIAAAAJ&hl=en).

## Funding as Lead PI

**CBCS Small Grants Scheme** (PI, $3,300), March 2026
: *Bringing animal tracking data from ecological research to applied conservation outcomes* (workshop).

**RZS NSW Paddy Pallin Science Grant** (PI, $10,000), November 2025
: *Tracking sympatric seabirds in the Capricornia Cays to improve conservation and management.*

**UQ Knowledge Exchange & Translation Fund** (PI, ~$104,000), October 2025
: *Tracking sympatric seabirds in the Great Barrier Reef to delineate Key Biodiversity Areas.* In collaboration with BirdLife Australia and Queensland Parks and Wildlife Service.

**Queensland-Smithsonian Fellowship** (PI, $23,000), August 2024
: *Quantifying migratory connectivity of Great Barrier Reef seabirds.* Collating existing knowledge of seabird migratory connectivity in the GBR to identify priority species and areas for future research, in collaboration with Dr Autumn-Lynn Harrison (Smithsonian National Zoo and Conservation Biology Institute).

**CBCS Small Grants Scheme** (PI, $5,000), April 2023
: *Developing Megavertebrate Conservation Research and Teaching at Heron Island* (workshop).

## Conference presentations & invited talks

**World Seabird Conference**, Hobart, September 2026
: *Seventy years of seabird connectivity across the Coral Sea.* [Talk]
: *Multi-colony tracking of wedge-tailed shearwaters to identify Marine KBAs in the Great Barrier Reef World Heritage Area.* [Poster, senior author]

**BirdLife Australia Seabird Webinar Series**, August 2026
: *World Nature Conservation Day: Using Scientific Data to Protect Seabirds.* [Invited talk, online]

**MoveBON Quarterly Connect**, June 2026
: *Steps Towards Important Marine Turtle Areas: Blue Corridors for Turtles at CMS COP.* [Invited talk, online]

**Centre for Marine Science TalkFest**, Brisbane, February 2026
: *Seventy years of seabird connectivity across the Great Barrier Reef and Coral Sea.* [Invited talk]

**Birds Queensland Meeting**, Brisbane, February 2026
: *Global- to local-scale seabird connectivity for understanding ecology and improving conservation outcomes.* [Invited talk]

**Ecological Society of Australia Annual Meeting**, Adelaide, November 2025
: *Integrating a first estimate of global marine migratory connectivity into conservation policy and practice.* [Talk within co-organised symposium on movement ecology for conservation]

**UQ Marine Society Research Night**, Brisbane, September 2025
: *Frequent Flyers of the Great Barrier Reef: Seabird Connectivity Across the Coral Sea.* [Invited talk]

**Oceania Seabird Symposium**, New Zealand, April 2025
: *Mapping Seabird Connectivity Across the Coral Sea.* [Talk]

**16th Conference of the Parties to the Convention on Biological Diversity (COP16)**, Cali, Colombia, October 2024
: *Action-oriented science to support management and conservation of biodiversity in the global ocean.* [Invited talk, side event coordinated by the Global Ocean Biodiversity Initiative]

**International Marine Conservation Congress 7**, Cape Town, South Africa, October 2024
: *Reviewing the role of migratory species in systematic conservation planning.* [Talk]

**Australian Marine Sciences Association Annual Meeting**, Hobart, September 2024
: *Megavertebrate migrations connect the global oceans: insights for policymakers.* [Talk]

**Australian National University Ecology and Evolution Seminar Series**, Canberra, August 2024
: *Foraging habitat segregation unlikely coevolved in the two sympatric* Phoebetria *albatrosses.* [Invited talk]

**14th Conference of the Parties to the Convention on Migratory Species (CMS COP14)**, Samarkand, Uzbekistan, February 2024
: *Marine Flyways: advancing coordinated conservation action for threatened migratory seabirds.* [Invited talk, side event coordinated by BirdLife International]

**Australian Ornithological Conference**, November 2023
: *Global synthesis of migratory connectivity in marine birds.* [Talk]

**Ecological Society of Australia Annual Conference**, December 2020
: *Habitat preferences in sympatry and allopatry of the* Phoebetria *albatrosses.* [Talk] Winner of the [Wiley Prize for outstanding spoken presentation](https://www.ecolsoc.org.au/news/esa2020-student-prize-winners/).

**British Ecological Society Annual Meeting**, December 2018
: *Spatiotemporal segregation of foraging habitat in Southern Ocean grey and white-chinned petrels.* [Poster]
